// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2WJX9k-2HZvjAu2RBxuavN-exehDAGzw',
    appId: '1:1065664592379:web:4ddc3d787371784445335e',
    messagingSenderId: '1065664592379',
    projectId: 'easy-shop-final-5ac94',
    authDomain: 'easy-shop-final-5ac94.firebaseapp.com',
    storageBucket: 'easy-shop-final-5ac94.firebasestorage.app',
    measurementId: 'G-B6DN43T9FG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOOuBmZpasRIXe51IJy4beN5mndEJ2tTo',
    appId: '1:1065664592379:android:df0a742ad4d207e145335e',
    messagingSenderId: '1065664592379',
    projectId: 'easy-shop-final-5ac94',
    storageBucket: 'easy-shop-final-5ac94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRRfU2ppa5_TaBz8RPJGrqCQjxL7SEHtM',
    appId: '1:1065664592379:ios:506598843a08985545335e',
    messagingSenderId: '1065664592379',
    projectId: 'easy-shop-final-5ac94',
    storageBucket: 'easy-shop-final-5ac94.firebasestorage.app',
    iosBundleId: 'com.easyshop.app.easyshop',
  );

}